version: "3"

services:
  brick-test:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    deploy:
      replicas: 3
    environment:
      - UUID={{.Task.Slot}}
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/api/v1/hostname || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
